export const specialCase = [
  {"AyatLen": 2,"SuratNo": 2, "AyatNo": 1, "AyatLong": "أَلِفْ لَامْ مِيمْ", "AyatShort": "الٓمٓ"},
  {"AyatLen": 2,"SuratNo": 3, "AyatNo": 1, "AyatLong": "أَلِفْ لَامْ مِيمْ", "AyatShort": "الٓمٓ"},
  {"AyatLen": 3,"SuratNo": 7, "AyatNo": 1, "AyatLong": "أَلِفْ لَامْ مِيمْ صَادْ", "AyatShort": "الٓمٓصٓ"},
  {"AyatLen": 2,"SuratNo": 10, "AyatNo": 1, "AyatLong": "أَلِفْ لَامْ رَا", "AyatShort": "الٓر"},
  {"AyatLen": 2,"SuratNo": 11, "AyatNo": 1, "AyatLong": "أَلِفْ لَامْ رَا", "AyatShort": "الٓر"},
  {"AyatLen": 2,"SuratNo": 12, "AyatNo": 1, "AyatLong": "أَلِفْ لَامْ رَا", "AyatShort": "الٓر"},
  {"AyatLen": 3,"SuratNo": 13, "AyatNo": 1, "AyatLong": "أَلِفْ لَامْ مِيمْ رَا", "AyatShort": "الٓمٓر"},
  {"AyatLen": 2,"SuratNo": 14, "AyatNo": 1, "AyatLong": "أَلِفْ لَامْ رَا", "AyatShort": "الٓر"},
  {"AyatLen": 2,"SuratNo": 15, "AyatNo": 1, "AyatLong": "أَلِفْ لَامْ رَا", "AyatShort": "الٓر"},
  {"AyatLen": 5,"SuratNo": 19, "AyatNo": 1, "AyatLong": "كَافْ هَا يَا عَيْنْ صَادْ", "AyatShort": "كٓهيعٓصٓ"},
  {"AyatLen": 2,"SuratNo": 20, "AyatNo": 1, "AyatLong": "طَاهَا", "AyatShort": "طه"},
  {"AyatLen": 3,"SuratNo": 26, "AyatNo": 1, "AyatLong": "طَا سِينْ مِيمْ", "AyatShort": "طسٓمٓ"},
  {"AyatLen": 2,"SuratNo": 27, "AyatNo": 1, "AyatLong": "طَا سِينْ", "AyatShort": "طسٓ"},
  {"AyatLen": 3,"SuratNo": 28, "AyatNo": 1, "AyatLong": "طَا سِينْ مِيمْ", "AyatShort": "طسٓمٓ"},
  {"AyatLen": 2,"SuratNo": 36, "AyatNo": 1, "AyatLong": "يَاسِينْ", "AyatShort": "يسٓ"},
  {"AyatLen": 1,"SuratNo": 38, "AyatNo": 1, "AyatLong": "صَادْ", "AyatShort": "صٓ"},
  {"AyatLen": 2,"SuratNo": 40, "AyatNo": 1, "AyatLong": "حَامِيمْ", "AyatShort": "حمٓ"},
  {"AyatLen": 2,"SuratNo": 41, "AyatNo": 1, "AyatLong": "حَامِيمْ", "AyatShort": "حمٓ"},
  {"AyatLen": 2,"SuratNo": 42, "AyatNo": 1, "AyatLong": "حَامِيمْ", "AyatShort": "حمٓ"},
  {"AyatLen": 2,"SuratNo": 43, "AyatNo": 1, "AyatLong": "حَامِيمْ", "AyatShort": "حمٓ"},
  {"AyatLen": 2,"SuratNo": 44, "AyatNo": 1, "AyatLong": "حَامِيمْ", "AyatShort": "حمٓ"},
  {"AyatLen": 2,"SuratNo": 45, "AyatNo": 1, "AyatLong": "حَامِيمْ", "AyatShort": "حمٓ"},
  {"AyatLen": 2,"SuratNo": 46, "AyatNo": 1, "AyatLong": "حَامِيمْ", "AyatShort": "حمٓ"},
  {"AyatLen": 3,"SuratNo": 42, "AyatNo": 2, "AyatLong": "عَيْنْ سِينْ قَافْ", "AyatShort": "عٓسٓقٓ"},
  {"AyatLen": 1,"SuratNo": 50, "AyatNo": 1, "AyatLong": "قَافْ", "AyatShort": "قٓ"},
  {"AyatLen": 1,"SuratNo": 68, "AyatNo": 1, "AyatLong": "نُونْ", "AyatShort": "نٓ"}
]